# Generated by Django 4.1.5 on 2023-07-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('date', models.DateTimeField()),
                ('content', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'blog_tb',
            },
        ),
    ]
