# Generated by Django 4.1.5 on 2023-07-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_slice',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
