# Generated by Django 4.1.5 on 2023-07-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_content_slice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_slice',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
